AC_PREREQ([2.71])
AC_INIT([nfc-mfsetuid], [1.0], [https://github.com/duament/nfc-mflock])
AC_CONFIG_SRCDIR([src/nfc-mfsetuid.c])
AC_CONFIG_HEADERS([config.h])

# Checks for programs.
AC_PROG_CC

# Checks for libraries.
AC_CHECK_LIB([nfc], [nfc_open])

# Checks for header files.
AC_CHECK_HEADERS([stdint.h])

# Checks for typedefs, structures, and compiler characteristics.
AC_CHECK_HEADER_STDBOOL
AC_TYPE_SIZE_T
AC_TYPE_UINT8_T

# Checks for library functions.

AC_CONFIG_FILES([Makefile])
AC_OUTPUT
